


#define CONTROL_EVENT_MOVE_EAST 1
#define CONTROL_EVENT_MOVE_SOUTH_EAST 2

#define CONTROL_EVENT_MOVE_SOUTH 3
#define CONTROL_EVENT_MOVE_SOUTH_WEST  4

#define CONTROL_EVENT_MOVE_WEST 5
#define CONTROL_EVENT_MOVE_NORTH_WEST 6

#define CONTROL_EVENT_MOVE_NORTH 7
#define CONTROL_EVENT_MOVE_NORTH_EAST 8



#define CONTROL_EVENT_DROP_BOMB 9

#define CONTROL_EVENT_DO_NOTHING 10